# Generated by Django 6.0.6 on 2026-06-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_job_benefits_job_key_responsibilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=models.TextField(default='Not specified'),
        ),
    ]
