# Generated by Django 6.0.6 on 2026-06-26 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_job_benefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='profile_picture')),
                ('headline', models.TextField()),
                ('about', models.TextField()),
                ('skills', models.TextField()),
                ('git_hub', models.URLField()),
                ('linkedin', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='resume/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('field_of_study', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=150)),
                ('start_year', models.CharField(max_length=50)),
                ('end_year', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
