# Generated by Django 6.0.6 on 2026-08-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Viewed', 'Viewed'), ('ShortListed', 'ShortListed'), ('Interview Scheduled', 'Interview Scheduled'), ('Technical Round', 'Technical Round'), ('HR Round', 'HR Round'), ('Offer Sent', 'Offer Sent'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Applied', max_length=50),
        ),
    ]
