# Generated by Django 6.0.6 on 2026-08-07 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_interviewschedule_recruiternote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Application Submitted', 'Application Submitted'), ('Candidate Shortlisted', 'Candidate Shortlisted'), ('Candidate Rejected', 'Candidate Rejected'), ('Interview Scheduled', 'Interview Scheduled'), ('Interview Updated', 'Interview Updated'), ('Interview Cancelled', 'Interview Cancelled'), ('Interview Completed', 'Interview Completed'), ('Offer Sent', 'Offer Sent'), ('Candidate Hired', 'Candidate Hired'), ('Email Sent', 'Email Sent'), ('Status Changed', 'Status Changed')], max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.job')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_round', models.CharField(choices=[('HR', 'HR'), ('Technical', 'Technical'), ('Managerial', 'Managerial'), ('Final', 'Final')], default='Technical', max_length=50)),
                ('time_zone', models.CharField(choices=[('Asia/Kolkata', 'IST (Asia/Kolkata)'), ('America/New_York', 'EST (America/New_York)'), ('America/Chicago', 'CST (America/Chicago)'), ('America/Denver', 'MST (America/Denver)'), ('America/Los_Angeles', 'PST (America/Los_Angeles)'), ('Europe/London', 'GMT (Europe/London)'), ('Europe/Berlin', 'CET (Europe/Berlin)'), ('Asia/Dubai', 'GST (Asia/Dubai)'), ('Asia/Singapore', 'SGT (Asia/Singapore)'), ('Asia/Tokyo', 'JST (Asia/Tokyo)'), ('Australia/Sydney', 'AEST (Australia/Sydney)'), ('UTC', 'UTC')], default='Asia/Kolkata', max_length=50)),
                ('meeting_type', models.CharField(choices=[('Google Meet', 'Google Meet'), ('Zoom', 'Zoom'), ('Microsoft Teams', 'Microsoft Teams'), ('Phone', 'Phone'), ('Office', 'Office')], default='Google Meet', max_length=50)),
                ('office_address', models.TextField(blank=True, default='')),
                ('interviewer_name', models.CharField(blank=True, default='', max_length=150)),
                ('recruiter_email', models.EmailField(blank=True, default='', max_length=254)),
                ('additional_instructions', models.TextField(blank=True, default='')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('send_email', models.BooleanField(default=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='accounts.interviewschedule')),
            ],
        ),
    ]
