# Generated by Django 6.0.6 on 2026-08-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_application_degree_application_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
